services:
  nestjs:
    build: .
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${NESTJS_PORT}:3000
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_started
      logto:
        condition: service_healthy
      mailhog:
          condition: service_started
      rustfs:
        condition: service_started
    networks:
      - app_network
  logto:
    depends_on:
      postgres:
        condition: service_healthy
    image: svhd/logto:${LOGTO_TAG}
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - ${LOGTO_PORT}:3001
      - ${LOGTO_ADMIN_PORT}:3002
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3001/oidc/.well-known/openid-configuration || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 40s
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - ${LOGTO_ENDPOINT}
      - ${LOGTO_ADMIN_ENDPOINT}
    networks:
      - app_network
    volumes:
      - logto_data:/data/db

  postgres:
    image: postgres:${POSTGRES_TAG}
    user: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    volumes:
      - postgre_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:${MONGO_TAG}
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db
  mailhog:
    image: mailhog/mailhog:${MAILHOG_TAG}
    restart: unless-stopped
    volumes:
      - ./mailhog_data:/mailhog/data
    networks:
      - app_network
    ports:
      - ${MAILHOG_PORT}:1025
      - ${MAILHOG_INTERFACE_PORT}:8025
  rustfs:
    image: rustfs/rustfs:${RUSTFS_TAG}
    environment:
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}
    volumes:
      - rustfs_data:/data
    networks:
      - app_network
    ports:
      - ${RUSTFS_PORT}:9001
      - ${RUSTFS_INTERFACE_PORT}:9000

volumes:
  mongodb_data:
  logto_data:
  postgre_data:
  rustfs_data:


networks:
  app_network:
    driver: bridge
